sudo: required
language: python
services: 
    - docker
python:
  - "2.7"
  - "3.5"
before_install:
    - ./run_docker.sh
install: 
    - "pip install -r requirements.txt"  
    - "pip install coveralls"
# command to run tests
script: pytest --cov=.
after_success: coveralls
