sudo: required
language: python
services: 
    - docker
python:
  - "2.7"
  - "3.5"
before_install:
    - docker build -t foobar .
    - docker run -td -p 8000:80 --name foobar_container foobar
    - docker ps -a
install: 
    - "pip install -r requirements.txt"  
    - "pip install coveralls"
# command to run tests
script: pytest --cov=.
after_success: coveralls
